# Generated by Django 3.2.5 on 2021-07-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_operations_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operations',
            name='user',
        ),
    ]
