# Generated by Django 3.2.5 on 2021-07-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_operations_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operations',
        ),
    ]
