# Generated by Django 3.2.5 on 2021-07-13 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_statement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('category', models.CharField(max_length=150)),
                ('operation_type', models.CharField(max_length=150)),
                ('isExpense', models.BooleanField()),
                ('bank_statement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation', to='bank_statement.bankstatement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
