# Generated by Django 3.2.6 on 2021-08-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operations',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='operations',
            name='isExpense',
        ),
        migrations.AddField(
            model_name='operations',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='operations',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='operations',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='operations',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
