# Generated by Django 3.2.5 on 2021-08-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20210807_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='details',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='operations',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='operations',
            name='category',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='operations',
            name='operation_type',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='operations',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
