# Generated by Django 3.2.6 on 2021-09-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20210912_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operations',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('ZAKUP PRZY UŻYCIU KARTY', 'ZAKUP PRZY UŻYCIU KARTY'), ('PŁATNOŚĆ WEB - KOD MOBILNY', 'PŁATNOŚĆ WEB - KOD MOBILNY'), ('PRZELEW WYCHODZĄCY', 'PRZELEW WYCHODZĄCY'), ('PRZELEW PRZYCHODZĄCY', 'PRZELEW PRZYCHODZĄCY'), ('PRZELEW NA TELEFON PRZYCHODZ. ZEW.', 'PRZELEW NA TELEFON PRZYCHODZ. ZEW.'), ('PRZELEW NA TELEFON WYCHODZĄCY ZEW.', 'PRZELEW NA TELEFON WYCHODZĄCY ZEW.'), ('PRZELEW PRZYCH. SYSTEMAT. WPŁYW', 'PRZELEW PRZYCH. SYSTEMAT. WPŁYW'), ('WYPŁATA W BANKOMACIE', 'WYPŁATA W BANKOMACIE'), ('WPŁATA GOTÓWKI WE WPŁATOMACIE', 'WPŁATA GOTÓWKI WE WPŁATOMACIE'), ('PRZELEW NA TELEFON PRZYCHODZ. WEW.', 'PRZELEW NA TELEFON PRZYCHODZ. WEW.')], max_length=150),
        ),
    ]
