# Generated by Django 3.2.6 on 2021-08-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='date',
            field=models.DateField(null=True, unique=True),
        ),
    ]
