# Generated by Django 3.2.6 on 2021-08-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statement', '0004_alter_bankstatement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='backend/bank_statement/store/'),
        ),
    ]
