# Generated by Django 3.2.6 on 2021-08-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statement', '0005_alter_bankstatement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
