# Generated by Django 3.2.6 on 2021-08-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statement', '0006_alter_bankstatement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='date_upload',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='date',
            field=models.DateField(null=True, unique=True),
        ),
    ]
