# Generated by Django 3.2.6 on 2021-08-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statement', '0007_auto_20210829_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
