# Generated by Django 3.2.6 on 2021-08-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statement', '0008_alter_bankstatement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
