# Generated by Django 3.2.6 on 2021-08-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statement', '0009_bankstatement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='date',
            field=models.DateField(null=True, unique=True),
        ),
    ]
